version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    env_file:
      - .env.dev
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
    volumes:
      - app_storage_dev:/app/storage
      - ./logs:/app/logs  # 개발시 로그 확인용
    depends_on: # postgres가 먼저 실행되어야합니다.
      - postgres
    networks:
      - app-network

  postgres:
    image: postgres:15
    env_file:
      - .env.dev
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "5432:5432"  # 개발시 외부 접근 허용
    networks:
      - app-network

volumes:
  app_storage_dev:
  postgres_data_dev:

networks:
  app-network:
