discodeit:
  repository:
    type: file   # jcf | file
    file-directory:
      binary-content-path: filestorage/binary-content.ser
      channel-path: filestorage/channel.ser
      message-path: filestorage/message.ser
      readStatus-path: filestorage/readStatus.ser
      user-path: filestorage/user.ser
      user-status-path: filestorage/userStatus.ser