# 아직 사용은 안해서 일단 만들어 놓았습니다.
spring:
  config:
    import: optional:file:.env.prod[.properties]
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
      idle-timeout: 60000
  boot:
    admin:
      client:
        url: ${SPRING_BOOT_ADMIN_CLIENT_URL}

server:
  port: 80

logging:
  level:
    com.sprint.mission.discodeit: info
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace