discodeit:
  storage:
    type: local
    local:
      root-path: filestorage/binary-content-storage

spring:
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        use_sql_comments: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  sql:
    init:
      mode: never

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        orm.jdbc.bind: TRACE
      springframework:
        data: DEBUG
    com:
      sprint:
        mission:
          discodeit: DEBUG


