name: CI

on:
  pull_request:
    branches:
      - part3-황지환-sprint7

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 체크아웃
        uses: actions/checkout@v4

      - name: JDK 17 설정
        uses: actions/setup-java@4
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: gradle

      - name: 테스트 실행
        run: ./gradlew test

      - name: Codecov 테스크 커버리지 업로드
        uses: codecov/codecov-action@v3
        with:
          files: build/reports/jacoco/test/jacocoTestReport.xml
